version: '3'
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb_cryptocurrency"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - /home/markus/IDEA/GoProjects/BlockchainMicroservices/database/mongodb/database:/data